<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.35">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; Descubriendo Patrones con Regresión Lineal – Notas de clase Business Analytics</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./capitulo7.html" rel="next">
<link href="./capitulo5.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-46f66b053e56abd73bb6e954d61a315b.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-22b4aaf4c2978829df3684e8f2c068db.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-46f66b053e56abd73bb6e954d61a315b.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-ffc4c3fc79587ee79da4865b6a08975e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-acff971833d9769290026d534105daaa.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-ffc4c3fc79587ee79da4865b6a08975e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="custom.css">
<link rel="stylesheet" href="capitulo6.css">
</head>

<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./capitulo6.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Descubriendo Patrones con Regresión Lineal</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Notas de clase Business Analytics</a> 
        <div class="sidebar-tools-main">
    <div class="dropdown">
      <a href="" title="Descargar" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Descargar"><i class="bi bi-download"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./Notas-de-clase-Business-Analytics.pdf">
              <i class="bi bi-file-pdf pe-1"></i>
            Descargar PDF
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./Notas-de-clase-Business-Analytics.epub">
              <i class="bi bi-journal pe-1"></i>
            Descargar ePub
            </a>
          </li>
      </ul>
    </div>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Alternar modo oscuro"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bienvenidos</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introducción: Descubriendo la Analítica de Datos</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./capitulo2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introducción a Variables y Datos</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./capitulo3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Explorando tus Datos con Estadísticos Descriptivos</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./capitulo4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Contando Historias Claras con Gráficos</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./capitulo5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Intervalos de Confianza y Pruebas de Hipótesis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./capitulo6.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Descubriendo Patrones con Regresión Lineal</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./capitulo7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Extensiones del modelo de regresión lineal</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./capitulo8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Modelos de probabilidad</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#una-primera-pista-con-la-regresión-simple" id="toc-una-primera-pista-con-la-regresión-simple" class="nav-link active" data-scroll-target="#una-primera-pista-con-la-regresión-simple"><span class="header-section-number">6.1</span> Una primera pista con la Regresión Simple</a></li>
  <li><a href="#es-realmente-importante-mi-coeficiente-significancia-estadística" id="toc-es-realmente-importante-mi-coeficiente-significancia-estadística" class="nav-link" data-scroll-target="#es-realmente-importante-mi-coeficiente-significancia-estadística"><span class="header-section-number">6.2</span> ¿Es realmente importante mi coeficiente? (significancia estadística)</a>
  <ul class="collapse">
  <li><a href="#el-planteamiento" id="toc-el-planteamiento" class="nav-link" data-scroll-target="#el-planteamiento"><span class="header-section-number">6.2.1</span> El planteamiento</a></li>
  <li><a href="#ejemplo-de-restaurante" id="toc-ejemplo-de-restaurante" class="nav-link" data-scroll-target="#ejemplo-de-restaurante"><span class="header-section-number">6.2.2</span> Ejemplo de restaurante 🍝</a></li>
  <li><a href="#la-prueba" id="toc-la-prueba" class="nav-link" data-scroll-target="#la-prueba"><span class="header-section-number">6.2.3</span> La prueba</a></li>
  <li><a href="#la-moraleja" id="toc-la-moraleja" class="nav-link" data-scroll-target="#la-moraleja"><span class="header-section-number">6.2.4</span> La moraleja</a></li>
  </ul></li>
  <li><a href="#midiendo-qué-tan-bien-funciona-mi-regresión" id="toc-midiendo-qué-tan-bien-funciona-mi-regresión" class="nav-link" data-scroll-target="#midiendo-qué-tan-bien-funciona-mi-regresión"><span class="header-section-number">6.3</span> Midiendo qué tan bien funciona mi regresión</a></li>
  <li><a href="#sumando-más-ingredientes-la-regresión-múltiple" id="toc-sumando-más-ingredientes-la-regresión-múltiple" class="nav-link" data-scroll-target="#sumando-más-ingredientes-la-regresión-múltiple"><span class="header-section-number">6.4</span> Sumando más ingredientes: la Regresión Múltiple</a>
  <ul class="collapse">
  <li><a href="#significancia-en-la-regresión-múltiple" id="toc-significancia-en-la-regresión-múltiple" class="nav-link" data-scroll-target="#significancia-en-la-regresión-múltiple"><span class="header-section-number">6.4.1</span> Significancia en la regresión múltiple</a></li>
  </ul></li>
  <li><a href="#conclusión" id="toc-conclusión" class="nav-link" data-scroll-target="#conclusión"><span class="header-section-number">6.5</span> Conclusión</a></li>
  <li><a href="#extensiones-del-modelo-de-regresión-lineal" id="toc-extensiones-del-modelo-de-regresión-lineal" class="nav-link" data-scroll-target="#extensiones-del-modelo-de-regresión-lineal"><span class="header-section-number">6.6</span> Extensiones del modelo de regresión lineal</a>
  <ul class="collapse">
  <li><a href="#cuando-los-ingredientes-se-combinan-interacciones" id="toc-cuando-los-ingredientes-se-combinan-interacciones" class="nav-link" data-scroll-target="#cuando-los-ingredientes-se-combinan-interacciones"><span class="header-section-number">6.6.1</span> Cuando los ingredientes se combinan: Interacciones</a></li>
  <li><a href="#relaciones-no-siempre-lineales" id="toc-relaciones-no-siempre-lineales" class="nav-link" data-scroll-target="#relaciones-no-siempre-lineales"><span class="header-section-number">6.6.2</span> Relaciones no siempre lineales</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Descubriendo Patrones con Regresión Lineal</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="img/reg_1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1"><img src="img/reg_1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%"></a></p>
</figure>
</div>
<p>Imagina que eres dueño de un restaurante 🍝.<br>
Cada día recibes clientes, vendes platos y al final de la semana te preguntas:</p>
<blockquote class="blockquote">
<p><strong>¿Qué hace que mis ventas suban o bajen?</strong><br>
¿Será el precio de los platos, la inversión en publicidad, o quizá los fines de semana festivos?</p>
</blockquote>
<p>Aquí entra en acción la <strong>regresión lineal</strong>, una herramienta que nos ayuda a descubrir patrones escondidos en los datos.</p>
<section id="una-primera-pista-con-la-regresión-simple" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="una-primera-pista-con-la-regresión-simple"><span class="header-section-number">6.1</span> Una primera pista con la Regresión Simple</h2>
<p>Empecemos simple: ¿qué pasa con tus ventas y el precio del menú?</p>
<p>En estos ejemplos, <strong>Ventas</strong> es el número de platos vendidos por semana, no el dinero recaudado. Es la variable que queremos explicar o predecir (<span class="math inline">\(Y\)</span>). <strong>Precio</strong> es el precio de un plato, medido en unidades monetarias, y es la variable que usamos como pista (<span class="math inline">\(X\)</span>). Cada punto del gráfico representa una semana.</p>
<p>Si anotas tus datos semana a semana y los pones en un gráfico como el de abajo, notarás que cuando el precio sube, las ventas tienden a bajar. La regresión lineal traza la <strong>mejor línea recta</strong> que explica esa relación.</p>
<p>¿Por qué una línea si los puntos están dispersos? Porque buscamos resumir la <strong>tendencia promedio</strong>: dos semanas con el mismo precio pueden tener ventas distintas. La línea da una predicción para ese precio; no promete acertar exactamente cada semana.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="img/reg_2.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Gráfico de dispersión ventas vs.&nbsp;precio"><img src="img/reg_2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%" alt="Gráfico de dispersión ventas vs.&nbsp;precio"></a></p>
</figure>
</div>
<figcaption>Gráfico de dispersión ventas vs.&nbsp;precio</figcaption>
</figure>
</div>
<p>El modelo distingue la parte que representa la línea y lo que queda fuera de ella:</p>
<p><span class="math display">\[
Ventas = b_0 + b_1 \times Precio + \varepsilon
\]</span></p>
<ul>
<li><strong><span class="math inline">\(b_0\)</span></strong>: el intercepto; ubica la altura de la recta. Corresponde a las ventas promedio cuando el precio es cero, aunque vender gratis esté fuera de los datos y esa interpretación no sea útil 🍕.<br>
</li>
<li><strong><span class="math inline">\(b_1\)</span></strong>: la <em>pendiente</em>; cuánto cambian las ventas promedio según el modelo por cada unidad adicional de precio.<br>
</li>
<li><strong><span class="math inline">\(\varepsilon\)</span></strong>: el ruido que la línea no puede explicar (clima, humor del chef, partidos de fútbol, etc.).</li>
</ul>
<p>👉 Si el modelo encuentra que:</p>
<p><span class="math display">\[
\hat{Ventas} = 500 - 25 \times Precio
\]</span></p>
<p>El sombrero en <span class="math inline">\(\hat{Ventas}\)</span> significa <strong>ventas predichas</strong>. Para usar la ecuación, reemplazamos el precio y hacemos la cuenta:</p>
<div class="table-responsive">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Precio</th>
<th>Cálculo</th>
<th>Platos predichos por semana</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>10</td>
<td><span class="math inline">\(500 - 25\times 10\)</span></td>
<td>250</td>
</tr>
<tr class="even">
<td>11</td>
<td><span class="math inline">\(500 - 25\times 11\)</span></td>
<td>225</td>
</tr>
<tr class="odd">
<td>12</td>
<td><span class="math inline">\(500 - 25\times 12\)</span></td>
<td>200</td>
</tr>
</tbody>
</table>
</div>
<p>Al pasar de 10 a 11, la predicción baja de 250 a 225: <strong>25 platos menos</strong>. Si el precio aumenta dos unidades, baja <span class="math inline">\(25\times 2=50\)</span> platos. Esa variación constante es la intuición de la pendiente de una recta.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>De la predicción al error
</div>
</div>
<div class="callout-body-container callout-body">
<p>Si con un precio de 10 se vendieron realmente 270 platos, el <strong>residuo</strong> es <span class="math inline">\(270-250=20\)</span>: el punto queda 20 platos por encima de la recta. Si se vendieron 230, el residuo es <span class="math inline">\(230-250=-20\)</span> y el punto queda por debajo. El residuo es la diferencia observable entre el dato y la predicción; <span class="math inline">\(\varepsilon\)</span> representa el error del modelo en la población.</p>
<p>La «mejor» recta por <strong>mínimos cuadrados</strong> es la que hace más pequeña la suma de los residuos al cuadrado. Los elevamos al cuadrado para que errores positivos y negativos no se cancelen y para penalizar más los errores grandes. Así elegimos una línea que se acerque al conjunto de puntos.</p>
</div>
</div>
<p>Esta relación describe los datos, pero por sí sola no demuestra que cambiar el precio cause esa caída: quizá las semanas con precios altos también tuvieron menos publicidad. Además, conviene predecir dentro del rango de precios observado; prolongar la recta demasiado puede producir resultados absurdos, como ventas negativas.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-pendiente-residuo" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Recta de ventas igual a 500 menos 25 por precio. De precio 10 a 11 la predicción baja de 250 a 225. A precio 10, una observación de 270 está 20 platos por encima de la predicción.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pendiente-residuo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="capitulo6_files/figure-html/fig-pendiente-residuo-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Figura&nbsp;6.1: La pendiente compara dos predicciones; el residuo compara una observación con su predicción."><img src="capitulo6_files/figure-html/fig-pendiente-residuo-1.png" class="img-fluid figure-img" style="width:100.0%" alt="Recta de ventas igual a 500 menos 25 por precio. De precio 10 a 11 la predicción baja de 250 a 225. A precio 10, una observación de 270 está 20 platos por encima de la predicción."></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pendiente-residuo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.1: La pendiente compara dos predicciones; el residuo compara una observación con su predicción.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Lee el gráfico en dos direcciones: <strong>hacia la derecha</strong>, la pendiente indica cómo cambia la predicción al cambiar el precio; <strong>hacia arriba o abajo</strong>, el residuo indica cuánto se alejó una semana de lo predicho.</p>
</section>
<section id="es-realmente-importante-mi-coeficiente-significancia-estadística" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="es-realmente-importante-mi-coeficiente-significancia-estadística"><span class="header-section-number">6.2</span> ¿Es realmente importante mi coeficiente? (significancia estadística)</h2>
<p>Hasta ahora vimos que un coeficiente <span class="math inline">\(b_1\)</span> nos dice cómo cambia <span class="math inline">\(Y\)</span> cuando <span class="math inline">\(X\)</span> sube una unidad.</p>
<p>Pero la gran pregunta es: <strong>¿la pendiente observada es suficientemente clara para distinguirla de las fluctuaciones de una muestra?</strong></p>
<p>Aquí entran las <strong>pruebas de hipótesis</strong> que estudiamos en el capítulo anterior. Con otras semanas obtendríamos una pendiente algo distinta; la prueba tiene en cuenta esa incertidumbre.</p>
<section id="el-planteamiento" class="level3" data-number="6.2.1">
<h3 data-number="6.2.1" class="anchored" data-anchor-id="el-planteamiento"><span class="header-section-number">6.2.1</span> El planteamiento</h3>
<ul>
<li><strong>Hipótesis nula (<span class="math inline">\(H_0\)</span>)</strong>: el coeficiente en la población es igual a 0. En el modelo simple, la recta de ventas promedio sería horizontal: conocer el precio no cambiaría la predicción.</li>
<li><strong>Hipótesis alternativa (<span class="math inline">\(H_1\)</span>)</strong>: el coeficiente en la población es diferente de 0. La recta de ventas promedio tendría una pendiente positiva o negativa.</li>
</ul>
<p>Para evaluar la evidencia, puedes usar el <strong>valor p (p-value)</strong>. Imagina que la pendiente poblacional fuera cero y recogiéramos muchas muestras similares: aun así, algunas mostrarían pendientes distintas de cero por azar. El valor p indica qué tan probable sería obtener un estadístico de prueba tan extremo como el observado, o más, <strong>si la hipótesis nula y los supuestos de la prueba fueran ciertos</strong>. No es la probabilidad de que el coeficiente sea cero.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Prueba de significancia estadística
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Si el valor p es menor que 0.05, el coeficiente es <strong>significativo al nivel del 5%</strong>: rechazamos <span class="math inline">\(H_0\)</span> y encontramos evidencia de una asociación lineal entre precio y ventas.</li>
<li>Si el valor p es mayor o igual que 0.05, no rechazamos <span class="math inline">\(H_0\)</span>: los datos no ofrecen suficiente evidencia para distinguir el coeficiente de cero. Esto no demuestra que sea cero.</li>
</ul>
</div>
</div>
</section>
<section id="ejemplo-de-restaurante" class="level3" data-number="6.2.2">
<h3 data-number="6.2.2" class="anchored" data-anchor-id="ejemplo-de-restaurante"><span class="header-section-number">6.2.2</span> Ejemplo de restaurante 🍝</h3>
<p>Supongamos que obtienes un nuevo modelo al recoger más datos e incluir publicidad (más adelante veremos cómo interpretar varias variables juntas). Aquí <strong>Publicidad</strong> se mide en centenas de unidades monetarias: gastar 200 se registra como <span class="math inline">\(Publicidad=2\)</span>.</p>
<p><span class="math display">\[
\hat{Ventas} = 400 - 20 \times Precio + 60 \times Publicidad
\]</span></p>
<ul>
<li>El coeficiente de <strong>Precio = -20</strong> indica una predicción de 20 platos menos por cada unidad adicional de precio, manteniendo fija la publicidad.<br>
</li>
<li>Pero, ¿y si esa relación negativa se debe solo a la casualidad en tus datos?</li>
</ul>
</section>
<section id="la-prueba" class="level3" data-number="6.2.3">
<h3 data-number="6.2.3" class="anchored" data-anchor-id="la-prueba"><span class="header-section-number">6.2.3</span> La prueba</h3>
<p>El software (R, Excel, Stata, etc.) hace un <strong>test t</strong> que compara el coeficiente con su <strong>error estándar</strong>, una medida de la incertidumbre con que lo estimamos. Para probar un coeficiente igual a cero, calcula <span class="math inline">\(t=\text{coeficiente estimado}/\text{error estándar}\)</span>.</p>
<p>Por ejemplo, una pendiente de <span class="math inline">\(-20\)</span> con error estándar de 5 está a cuatro errores estándar de cero (<span class="math inline">\(t=-4\)</span>); con error estándar de 25 está a menos de uno (<span class="math inline">\(t=-0.8\)</span>). Aunque la pendiente es la misma, el primer caso ofrece evidencia más clara de una asociación. El p-valor se obtiene a partir de ese estadístico y de los grados de libertad del modelo.</p>
<ul>
<li>Si el <strong>p-valor &lt; 0.05</strong>, rechazamos la hipótesis nula. Encontramos evidencia de una asociación entre precio y ventas, controlando por publicidad.</li>
<li>Si el <strong>p-valor ≥ 0.05</strong>, no tenemos suficiente evidencia. La estimación es compatible con un coeficiente poblacional de cero; también puede haber una relación que estos datos no permitan detectar con claridad.</li>
</ul>
</section>
<section id="la-moraleja" class="level3" data-number="6.2.4">
<h3 data-number="6.2.4" class="anchored" data-anchor-id="la-moraleja"><span class="header-section-number">6.2.4</span> La moraleja</h3>
<p>Conviene separar dos preguntas: <strong>¿de qué tamaño es la asociación estimada?</strong> (el coeficiente) y <strong>¿qué evidencia tenemos de que difiere de cero?</strong> (la prueba). Una asociación pequeña puede ser significativa con muchos datos, y una grande puede estimarse con mucha incertidumbre. La significancia estadística no garantiza importancia para el negocio ni demuestra causalidad.</p>
<p>👉 En negocios, antes de tomar decisiones (subir precios, invertir en publicidad, lanzar una promo), debemos considerar el tamaño de la asociación, su incertidumbre y si la comparación permite atribuir los cambios a esa decisión.</p>
</section>
</section>
<section id="midiendo-qué-tan-bien-funciona-mi-regresión" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="midiendo-qué-tan-bien-funciona-mi-regresión"><span class="header-section-number">6.3</span> Midiendo qué tan bien funciona mi regresión</h2>
<p>No basta con tener la línea (regresión), también queremos saber <strong>qué tan buena es</strong>.</p>
<p>Para eso usamos el famoso <strong><span class="math inline">\(R^2\)</span></strong>, también llamado coeficiente de determinación. La idea es comparar dos maneras de predecir las semanas que usamos para ajustar el modelo:</p>
<ol type="1">
<li><strong>Sin usar el precio:</strong> predecir siempre el promedio de ventas, como una línea horizontal.</li>
<li><strong>Usando el precio:</strong> predecir con la recta de regresión.</li>
</ol>
<p>En una regresión por mínimos cuadrados con intercepto, <span class="math inline">\(R^2\)</span> mide cuánto se reduce la suma de errores al cuadrado al pasar de la primera opción a la segunda. Si era 10 000 al usar el promedio y queda en 2 000 al usar la recta:</p>
<p><span class="math display">\[
R^2=1-\frac{2\,000}{10\,000}=0.8
\]</span></p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-r2-promedio" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Dos gráficos con las mismas cinco semanas. Arriba, una línea horizontal en 250 platos produce errores cuadrados que suman 10000. Abajo, una recta descendente reduce la suma a 2000: R cuadrado es 0.8.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-r2-promedio-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="capitulo6_files/figure-html/fig-r2-promedio-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="Figura&nbsp;6.2: Los mismos datos, dos formas de predecir. Los segmentos verticales muestran los errores que elevamos al cuadrado y sumamos."><img src="capitulo6_files/figure-html/fig-r2-promedio-1.png" class="img-fluid figure-img" style="width:100.0%" alt="Dos gráficos con las mismas cinco semanas. Arriba, una línea horizontal en 250 platos produce errores cuadrados que suman 10000. Abajo, una recta descendente reduce la suma a 2000: R cuadrado es 0.8."></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-r2-promedio-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.2: Los mismos datos, dos formas de predecir. Los segmentos verticales muestran los errores que elevamos al cuadrado y sumamos.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Los puntos no cambian entre los dos paneles: cambia la regla de predicción. Al usar el precio, la suma de errores al cuadrado baja de 10 000 a 2 000, una reducción del 80%.</p>
<ul>
<li>Si <span class="math inline">\(R^2 = 0.8\)</span> en el modelo simple, la recta con precio recoge el 80% de la variación de las ventas alrededor de su promedio <strong>en la muestra utilizada</strong>. En el modelo múltiple, ese porcentaje corresponde al conjunto de variables.<br>
</li>
<li>El 20% restante queda en los residuos: puede incluir clima, competencia, azar u otros patrones que el modelo no recoge. El <span class="math inline">\(R^2\)</span> no identifica cuál de estas razones lo explica.</li>
</ul>
<p>Si <span class="math inline">\(R^2 = 0\)</span>, la recta no mejora la predicción frente al promedio en esa muestra. Aun así, podría existir un patrón curvo que una recta no capture.</p>
<p>Si <span class="math inline">\(R^2 = 1\)</span>, todas las observaciones de la muestra quedan sobre la línea: los residuos son cero. Eso no garantiza acertar en semanas futuras.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Piensa en <span class="math inline">\(R^2\)</span> como una medida de cuánto mejora el ajuste frente a usar solo el promedio. Un <span class="math inline">\(R^2=0.8\)</span> <strong>no significa acertar el 80% de las semanas</strong>, ni que el precio cause el 80% de las ventas. Para evaluar predicciones futuras necesitamos comprobar los errores en datos que no se usaron para ajustar el modelo.</p>
</div>
</div>
</section>
<section id="sumando-más-ingredientes-la-regresión-múltiple" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="sumando-más-ingredientes-la-regresión-múltiple"><span class="header-section-number">6.4</span> Sumando más ingredientes: la Regresión Múltiple</h2>
<p>En la vida real, tus ventas no dependen solo del precio.<br>
En tu restaurante también influyen otros “ingredientes” del negocio:</p>
<ul>
<li>el <strong>precio</strong> del menú,<br>
</li>
<li>el <strong>dinero invertido en publicidad</strong>,<br>
</li>
<li>y si fue o no una <strong>semana festiva</strong>.</li>
</ul>
<p>La regresión múltiple nos permite poner todos esos factores en la misma receta estadística. Conservamos la publicidad en centenas de unidades monetarias y definimos <strong>Festivo = 1</strong> para una semana festiva y <strong>Festivo = 0</strong> para una que no lo es. Supongamos que tus datos arrojan:</p>
<p><span class="math display">\[
\begin{aligned}
\hat{Ventas} ={}&amp; 400 - 20 \times Precio \\
&amp;+ 60 \times Publicidad + 15 \times Festivo
\end{aligned}
\]</span></p>
<p>Interpretación, manteniendo constantes las demás variables del modelo:</p>
<ul>
<li>Cada unidad adicional de precio se asocia con 20 platos menos por semana.<br>
</li>
<li>Cada 100 unidades monetarias adicionales en publicidad se asocian con 60 platos más.<br>
</li>
<li>Una semana festiva tiene una predicción de 15 platos más que una no festiva.</li>
</ul>
<p>Para verlo, partamos de una semana con precio de 10, publicidad de 200 y sin festivo:</p>
<p><span class="math display">\[
\hat{Ventas}=400-20\times10+60\times2+15\times0=320
\]</span></p>
<p>Ahora cambiamos <strong>una sola característica cada vez</strong> respecto de esa semana:</p>
<div class="table-responsive">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Escenario</th>
<th>Precio</th>
<th>Publicidad (centenas)</th>
<th>Festivo</th>
<th>Platos predichos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Semana de partida</td>
<td>10</td>
<td>2</td>
<td>0</td>
<td>320</td>
</tr>
<tr class="even">
<td>Solo cambia el precio</td>
<td>11</td>
<td>2</td>
<td>0</td>
<td>300</td>
</tr>
<tr class="odd">
<td>Solo cambia la publicidad</td>
<td>10</td>
<td>3</td>
<td>0</td>
<td>380</td>
</tr>
<tr class="even">
<td>Solo cambia el festivo</td>
<td>10</td>
<td>2</td>
<td>1</td>
<td>335</td>
</tr>
</tbody>
</table>
</div>
<p>Las diferencias frente a 320 son precisamente <span class="math inline">\(-20\)</span>, <span class="math inline">\(+60\)</span> y <span class="math inline">\(+15\)</span>. Esto es lo que significa <strong>mantener lo demás constante</strong>: comparar las predicciones de dos semanas iguales en las otras variables del modelo.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Plantilla de interpretación (ceteris paribus): significa que por cada unidad que aumente <strong>variable</strong>, la <strong>variable dependiente</strong> cambia en promedio <strong>coeficiente</strong> unidades, manteniendo constantes las demás variables.</p>
<p>Ejemplo: por cada unidad que aumenta el precio, las ventas semanales predichas disminuyen en promedio 20 platos, manteniendo la publicidad y la condición de semana festiva constantes.</p>
</div>
</div>
<p>En otras palabras, la regresión múltiple permite <strong>comparar teniendo en cuenta varias características a la vez</strong>. Si las semanas de precios bajos también tuvieron más publicidad, el modelo simple puede mezclar ambas asociaciones. Incluir publicidad ayuda a distinguirlas, pero no controla automáticamente factores que no medimos ni convierte la comparación en un experimento.</p>
<section id="significancia-en-la-regresión-múltiple" class="level3" data-number="6.4.1">
<h3 data-number="6.4.1" class="anchored" data-anchor-id="significancia-en-la-regresión-múltiple"><span class="header-section-number">6.4.1</span> Significancia en la regresión múltiple</h3>
<p>En regresión múltiple evaluamos la significancia de cada coeficiente de la misma manera que en la regresión simple: mediante un estadístico t y su p-valor. Cada coeficiente se interpreta <strong>ceteris paribus</strong> (manteniendo las demás variables constantes), por eso es importante no mezclar la interpretación de los efectos.</p>
<p>Ejemplo (resumen):</p>
<ul>
<li>Usamos el mismo modelo de precio, publicidad y festivo de la ecuación anterior.</li>
<li>p-valores (ej.): Precio <span class="math inline">\(p&lt;0.01\)</span> (significativo), Publicidad <span class="math inline">\(p=0.18\)</span> (no significativo), Festivo <span class="math inline">\(p=0.03\)</span> (significativo)</li>
</ul>
<p>Aunque el coeficiente de publicidad sea 60, su p-valor (<span class="math inline">\(p=0.18\)</span>) indica que, al nivel del 5%, no hay suficiente evidencia para distinguir su coeficiente poblacional de cero una vez controlamos por precio y festivo. <strong>La estimación sigue siendo 60, no se convierte en 0</strong>, y sigue entrando en las predicciones del modelo ajustado. Podríamos necesitar más datos o mayor variación en publicidad para estimarla con precisión; no podemos concluir que la publicidad sea inútil.</p>
</section>
</section>
<section id="conclusión" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="conclusión"><span class="header-section-number">6.5</span> Conclusión</h2>
<p>La regresión lineal, ya sea simple o múltiple, funciona como una lupa 🔍:<br>
te ayuda a <strong>resumir cómo se relacionan las variables con tus resultados</strong>, hacer predicciones y evaluar la incertidumbre de esas relaciones.</p>
<p>En el restaurante esto significa tomar decisiones con más confianza:<br>
¿bajo precios?, ¿aumento el presupuesto en publicidad?, ¿aprovecho mejor los festivos?</p>
<p>👉 La magia está en que no tienes que adivinar. Los datos te cuentan la historia, y la regresión es el traductor.</p>
</section>
<section id="extensiones-del-modelo-de-regresión-lineal" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="extensiones-del-modelo-de-regresión-lineal"><span class="header-section-number">6.6</span> Extensiones del modelo de regresión lineal</h2>
<p>Hasta ahora, hemos usado modelos de regresión lineal “simples” para predecir ventas en tu restaurante según precio, publicidad o si era semana festiva. Pero el mundo real es más complejo: las variables <strong>pueden interactuar</strong> entre sí y la relación con las ventas <strong>no siempre es lineal</strong>.</p>
<p>Veamos cómo ampliar la receta de la regresión lineal para capturar estos matices.</p>
<hr>
<section id="cuando-los-ingredientes-se-combinan-interacciones" class="level3" data-number="6.6.1">
<h3 data-number="6.6.1" class="anchored" data-anchor-id="cuando-los-ingredientes-se-combinan-interacciones"><span class="header-section-number">6.6.1</span> Cuando los ingredientes se combinan: Interacciones</h3>
<p>Imagina que lanzas un nuevo plato y quieres saber cómo influye el <strong>precio</strong> en las ventas. Pero tal vez el impacto del precio depende de otra variable, por ejemplo, si hiciste o no <strong>publicidad</strong>.</p>
<ul>
<li>Si no hay publicidad, un descuento en el precio podría no atraer a muchos clientes.<br>
</li>
<li>Si sí hay publicidad, ese mismo descuento puede disparar las ventas.</li>
</ul>
<p>Esto se llama <strong>interacción</strong>: el efecto de una variable depende del valor de otra.</p>
<p>Para este ejemplo, cambiamos la forma de registrar <strong>Publicidad</strong>: ahora vale <strong>1 si hubo campaña y 0 si no la hubo</strong>, en lugar de medir el gasto en centenas. Así podemos comparar dos rectas, una para cada situación.</p>
<p><span class="math display">\[
\begin{aligned}
Ventas ={}&amp; b_0 + b_1 \times Precio + b_2 \times Publicidad \\
&amp;+ b_3 \times (Precio \times Publicidad) + \varepsilon
\end{aligned}
\]</span></p>
<p>El término <span class="math inline">\(b_3\)</span> mide cuánto cambia el efecto del precio cuando hay publicidad.</p>
<p>Supongamos que la ecuación estimada es:</p>
<p><span class="math display">\[
\begin{aligned}
\hat{Ventas} ={}&amp; 400-10\times Precio+100\times Publicidad \\
&amp;-10\times(Precio\times Publicidad)
\end{aligned}
\]</span></p>
<p>Sustituimos el indicador:</p>
<ul>
<li><strong>Sin campaña (<span class="math inline">\(Publicidad=0\)</span>):</strong> los términos con publicidad desaparecen y queda <span class="math inline">\(\hat{Ventas}=400-10\times Precio\)</span>.</li>
<li><strong>Con campaña (<span class="math inline">\(Publicidad=1\)</span>):</strong> queda <span class="math inline">\(\hat{Ventas}=500-20\times Precio\)</span>.</li>
</ul>
<p>Al bajar el precio de 10 a 9, la primera recta pasa de 300 a 310 platos y la segunda de 300 a 320. El mismo descuento se asocia con <strong>10 platos adicionales sin campaña y 20 con campaña</strong>. El coeficiente de interacción, <span class="math inline">\(-10\)</span>, es la diferencia entre las pendientes: <span class="math inline">\(-20-(-10)=-10\)</span>. Sin interacción, las dos rectas tendrían la misma pendiente.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-interaccion-publicidad" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A precio 10, ambas rectas predicen 300 platos. Al bajar a 9, la recta sin campaña predice 310 y la recta con campaña predice 320.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-interaccion-publicidad-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="capitulo6_files/figure-html/fig-interaccion-publicidad-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5" title="Figura&nbsp;6.3: Con interacción, las rectas tienen pendientes distintas: el mismo descuento cambia la predicción en cantidades diferentes."><img src="capitulo6_files/figure-html/fig-interaccion-publicidad-1.png" class="img-fluid figure-img" style="width:100.0%" alt="A precio 10, ambas rectas predicen 300 platos. Al bajar a 9, la recta sin campaña predice 310 y la recta con campaña predice 320."></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-interaccion-publicidad-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.3: Con interacción, las rectas tienen pendientes distintas: el mismo descuento cambia la predicción en cantidades diferentes.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Intuición:</strong> no todos los ingredientes de tu receta funcionan igual por separado. A veces lo que importa es la mezcla.</p>
</div>
</div>
<hr>
</section>
<section id="relaciones-no-siempre-lineales" class="level3" data-number="6.6.2">
<h3 data-number="6.6.2" class="anchored" data-anchor-id="relaciones-no-siempre-lineales"><span class="header-section-number">6.6.2</span> Relaciones no siempre lineales</h3>
<p>Una recta supone que cada unidad adicional de precio cambia la predicción en la misma cantidad. Pero esa variación podría ser diferente según el precio de partida. Por ejemplo:</p>
<ul>
<li>Pasar de un precio de 5 a 6 podría reducir la predicción en unos 19 platos.<br>
</li>
<li>Pasar de 10 a 11 podría reducirla en unos 29 platos.</li>
</ul>
<p>En ambos casos el precio sube una unidad, pero la caída es distinta. Eso dibuja una <strong>curva</strong> en vez de una recta.</p>
<p>Para capturar ese patrón podemos agregar un <strong>término cuadrático</strong> al modelo:</p>
<p><span class="math display">\[
Ventas = b_0 + b_1 \times Precio + b_2 \times Precio^2 + \varepsilon
\]</span></p>
<ul>
<li><span class="math inline">\(b_1\)</span> acompaña al precio, pero ya no se interpreta por sí solo como el cambio por una unidad: al cambiar el precio también cambia su cuadrado.<br>
</li>
<li><span class="math inline">\(b_2\)</span> permite que la curva se doble hacia arriba o hacia abajo.</li>
</ul>
<p>Por ejemplo, con <span class="math inline">\(\hat{Ventas}=500-8\times Precio-Precio^2\)</span>, un precio de 5 da <span class="math inline">\(500-40-25=435\)</span> platos y uno de 6 da <span class="math inline">\(500-48-36=416\)</span>: una caída de 19. De 10 a 11, las predicciones pasan de 320 a 291: una caída de 29. <strong>Para interpretar el cambio, evaluamos la ecuación completa en ambos precios y restamos.</strong></p>
<p>Aunque la gráfica sea curva, seguimos hablando de regresión lineal porque los coeficientes <span class="math inline">\(b_0\)</span>, <span class="math inline">\(b_1\)</span> y <span class="math inline">\(b_2\)</span> entran sumando, cada uno multiplicado por una variable conocida (<span class="math inline">\(Precio\)</span> o <span class="math inline">\(Precio^2\)</span>).</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Intuición:</strong> en una recta, cada paso a la derecha implica el mismo cambio vertical. En una curva, ese cambio depende de dónde empezamos. Agregar <span class="math inline">\(Precio^2\)</span> permite representar esa diferencia; no garantiza que exista un precio óptimo dentro del rango observado.</p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-grafico-cuadratico" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Semanas simuladas alrededor de una curva descendente. La curva es más inclinada a precios altos: de 5 a 6 se pierden 19 platos predichos y de 10 a 11 se pierden 29.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-grafico-cuadratico-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="capitulo6_files/figure-html/fig-grafico-cuadratico-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6" title="Figura&nbsp;6.4: Relación cuadrática entre precio y ventas (ejemplo simulado)"><img src="capitulo6_files/figure-html/fig-grafico-cuadratico-1.png" class="img-fluid figure-img" style="width:100.0%" alt="Semanas simuladas alrededor de una curva descendente. La curva es más inclinada a precios altos: de 5 a 6 se pierden 19 platos predichos y de 10 a 11 se pierden 29."></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-grafico-cuadratico-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.4: Relación cuadrática entre precio y ventas (ejemplo simulado)
</figcaption>
</figure>
</div>
</div>
</div>
<p>Los puntos representan semanas con variación alrededor del promedio y la curva azul muestra la relación usada para simularlos. La curva se hace más inclinada hacia abajo conforme aumenta el precio: cada unidad adicional se asocia con una caída mayor en las ventas promedio, dentro del rango mostrado.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./capitulo5.html" class="pagination-link" aria-label="Intervalos de Confianza y Pruebas de Hipótesis">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Intervalos de Confianza y Pruebas de Hipótesis</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./capitulo7.html" class="pagination-link" aria-label="Extensiones del modelo de regresión lineal">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Extensiones del modelo de regresión lineal</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>