project:
  type: book

book:
  title: "Notas de clase Business Analytics"
  author: "Daniel Parra"
  date: "16/7/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand



